name: your_app
description: "Rian's Flutter Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  provider: ^6.0.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.3
  flutter_cache_manager: ^3.4.1
  http: ^1.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # <-- Added this line

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png" # (optional, for Android adaptive icons)
  adaptive_icon_background: "0xFF2575FC" # (optional, background color)

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png  # Ensure the icon exists in this path

